#ifdef GETSET_DEFINE_TYPE
	GETSET_DEFINE_TYPE(char)
	GETSET_DEFINE_TYPE(unsigned char)
	GETSET_DEFINE_TYPE(short)
	GETSET_DEFINE_TYPE(unsigned short)
	GETSET_DEFINE_TYPE(int)
	GETSET_DEFINE_TYPE(unsigned)
	GETSET_DEFINE_TYPE(long)
	GETSET_DEFINE_TYPE(unsigned long)
	GETSET_DEFINE_TYPE(bool)
	GETSET_DEFINE_TYPE(float)
	GETSET_DEFINE_TYPE(double)
	#undef GETSET_DEFINE_TYPE
#endif
